### PR TITLE
Issue 94: Allow ftp:// organization urls

### LINKED ISSUE #94: Organizations FTP URL has malformed links
From an email on the listserv. I've verified that the ftp option writes an http url so the ftp://ftp.site.com is incorrectly written. 

> In the Organizations Module, I would like to add an ftp "shortcut" in the "login to url" space.
> 
> When I put in ftp://ftp.xxxxx.com
> 
> and use the arrow (link) to go there, I am directed to a local library page with a "page not found" error.
> 
> Is there any way to insert a shortcut to the ftp site (without copy & paste)?

### PR DESCRIPTION
**Pull request by queryluke**
Fixes #94 

## Fix
Instead of searching for a missing `http` string, instead search for a missing protocol `://`
Additionally, added CSS to allow urls to wrap. Very long urls would bleed over to the helpful links section

## Testing
In the organizations module, add an ftp url as the company url or the login url (login url under Accounts).

### CODE REVIEW

File: organizations/ajax_htmldata.php [hunk 1]
```diff
@@ -579,8 +581,8 @@ function generateDowntimeHTML($downtime) {
 				<?php if ($externalLogin['loginURL']) { ?>
 				<tr>
 				<td style='vertical-align:top;text-align:left;'><?php echo _("Login URL:");?></td>
-				<td><?php echo $externalLogin['loginURL'];
-					if (strpos($externalLogin['loginURL'], 'http') !== 0) {
+				<td style="word-break: break-all;"><?php echo $externalLogin['loginURL'];
+					if (strpos($externalLogin['loginURL'], '://') !== 0) {
```
Comment (veggiematts) [inline organizations/ajax_htmldata.php]: This is wrong. We should add http:// in front of the URL if :// is not found. Should be:
`if (strpos($externalLogin['loginURL'], '://') === false) {`
(otherwise we end up with "http://ftp://")
